#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
  *)
    systemctl preset flecs-webapp
    systemctl is-enabled flecs-webapp >/dev/null && systemctl start flecs-webapp || true
    ;;
esac

exit 0
