name: Build and Push

on:
  workflow_call:
    inputs:
      submodules:
        type: string
        default: 'false'
      make_target:
        type: string
        required: true
      version_suffix:
        type: string
        default: ''
      named_tag:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: ${{ inputs.submodules }}

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22.x

      - name: build
        run: make ${{ inputs.make_target }}

      - name: archive raw artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: build
          path: dist/
          retention-days: 1

  docker:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: ${{ inputs.submodules }}

      - name: download raw artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build
          path: dist/

      - name: Login to container registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: cr.flecs.tech
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_AUTH }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Determine version
        id: version
        run: echo "value=$(cat package.json | jq -r '.version')${{ inputs.version_suffix }}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        env:
          VERSION: ${{ steps.version.outputs.value }}
          NAMED_TAG: ${{ inputs.named_tag }}
        with:
          source: .
          files: docker-bake.hcl
          push: true
