name: Develop

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: build
        run: make dev-build
      - name: archive raw artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 1

  docker:
    needs: build
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_AUTH: ${{ secrets.REGISTRY_AUTH }}
      VERSION_SPECIAL: -dev

    steps:
      - uses: actions/checkout@v3
      - name: download raw artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build Docker image
        run: make docker_${{ matrix.arch }}

  docker-hub:
    needs: docker
    runs-on: ubuntu-22.04

    env:
      VERSION_SPECIAL: -dev

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_AUTH }}
      - name: Pull images
        run: |
          docker pull flecs/webapp:$(make version)-amd64
          docker pull flecs/webapp:$(make version)-arm64
          docker pull flecs/webapp:$(make version)-armhf
      - name: Create Docker manifest
        run: |
          docker manifest create flecs/webapp:$(make version) flecs/webapp:$(make version)-amd64 flecs/webapp:$(make version)-arm64 flecs/webapp:$(make version)-armhf
      - name: Push Docker manifest
        run: |
          docker manifest push flecs/webapp:$(make version)

  package:
    needs: docker
    runs-on: ubuntu-22.04

    env:
      VERSION_SPECIAL: -dev

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]

    steps:
      - uses: actions/checkout@v3
      - name: package
        run: |
          make deb-pkg_${{ matrix.arch }}
      - name: Deploy packages
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "*.deb"
          target: "${{ secrets.MP_GITHUB_DEVELOP_DIR }}/deb/"
      - name: Deploy latest file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MP_GITHUB_SERVER }}
          username: ${{ secrets.MP_GITHUB_USER }}
          key: ${{ secrets.MP_GITHUB_SSH_KEY }}
          passphrase: ${{ secrets.MP_GITHUB_SSH_KEY_PW }}
          source: "latest_flecs-webapp_*"
          target: "${{ secrets.MP_GITHUB_DEVELOP_DIR }}/"
