name: Develop

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build:test --if-present
      - name: archive raw artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  docker:
    needs: build
    runs-on: ubuntu-20.04

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_AUTH: ${{ secrets.REGISTRY_AUTH }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: download raw artifacts
        uses: actions/download-artifact@v2
      - name: build and push
        run: |
          make docker

  package:
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    steps:
      - uses: actions/checkout@v2

      - name: build and push
        run: |
          make deb-pkg

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "*.deb"
          target: ${{ secrets.SSH_DEVELOP_TARGET_DIR }}
