name: Develop

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      make_target: dev-build
      version_suffix: '-dev'
      named_tag: develop
    secrets: inherit
