name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      submodules: recursive
      make_target: build
      named_tag: latest
    secrets: inherit
