name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build:production --if-present
      - name: archive raw artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
          retention-days: 1

  package:
    runs-on: ubuntu-20.04
    container: flecs/flecs-build

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_AUTH: ${{ secrets.REGISTRY_AUTH }}

    steps:
      - uses: actions/checkout@v2

      - name: download raw artifacts
        uses: actions/download-artifact@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: docker
        run: |
          make NDEBUG=1 docker

      - name: package
        run: |
          make NDEBUG=1 deb-pkg

      - name: archive packages
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            **/*.deb
          retention-days: 3
