name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  special-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        special: ["wm"]

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_AUTH: ${{ secrets.REGISTRY_AUTH }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
          driver-opts: image=moby/buildkit:v0.11.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: build
        run: |
          make VERSION_SPECIAL=-${{ matrix.special }} special_${{ matrix.special }}
          make VERSION_SPECIAL=-${{ matrix.special }} build
      - name: archive raw artifacts
        uses: actions/upload-artifact@v3
        with:
          name: special-build
          path: build/
          retention-days: 1

  special-docker:
    needs: special-build
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: ["amd64", "armhf", "arm64"]
        special: ["wm"]

    env:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_AUTH: ${{ secrets.REGISTRY_AUTH }}

    steps:
      - uses: actions/checkout@v3
      - name: download raw artifacts
        uses: actions/download-artifact@v3
        with:
          name: special-build
          path: build/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
          driver-opts: image=moby/buildkit:v0.11.0
      - name: build Docker image
        run: |
          make VERSION_SPECIAL=-${{ matrix.special }} special_${{ matrix.special }}
          make VERSION_SPECIAL=-${{ matrix.special }} docker_${{ matrix.arch }}

  special-docker-hub:
    needs: special-docker
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        special: ["wm"]

    env:
      VERSION_SPECIAL: -${{ matrix.special }}

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_AUTH }}
      - name: Pull images
        run: |
          docker pull --platform=linux/amd64 flecs/webapp:$(make version)-amd64
          docker pull --platform=linux/arm64 flecs/webapp:$(make version)-arm64
          docker pull --platform=linux/armhf flecs/webapp:$(make version)-armhf
      - name: Create Docker manifest
        run: |
          docker manifest create flecs/webapp:$(make version) flecs/webapp:$(make version)-amd64 flecs/webapp:$(make version)-arm64 flecs/webapp:$(make version)-armhf
      - name: Push Docker manifest
        run: |
          docker manifest push flecs/webapp:$(make version)
